import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { CommonValueConverter } from '../common/valueConverter.js';
import { MermaidGeneratedSharedModule, NeuralNetworkGeneratedModule } from '../generated/module.js';
import { NeuralNetworkTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `NeuralNetwork` services.
 */
interface NeuralNetworkAddedServices {
  parser: {
    TokenBuilder: NeuralNetworkTokenBuilder;
    ValueConverter: CommonValueConverter;
  };
}

/**
 * Union of Langium default services and `NeuralNetwork` services.
 */
export type NeuralNetworkServices = LangiumCoreServices & NeuralNetworkAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `NeuralNetwork` services.
 */
export const NeuralNetworkModule: Module<
  NeuralNetworkServices,
  PartialLangiumCoreServices & NeuralNetworkAddedServices
> = {
  parser: {
    TokenBuilder: () => new NeuralNetworkTokenBuilder(),
    ValueConverter: () => new CommonValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createNeuralNetworkServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  NeuralNetwork: NeuralNetworkServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const NeuralNetwork: NeuralNetworkServices = inject(
    createDefaultCoreModule({ shared }),
    NeuralNetworkGeneratedModule,
    NeuralNetworkModule
  );
  shared.ServiceRegistry.register(NeuralNetwork);
  return { shared, NeuralNetwork };
}
