import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { CommonValueConverter } from '../common/valueConverter.js';
import {
  MermaidGeneratedSharedModule,
  TestSlidesDiagramGeneratedModule,
} from '../generated/module.js';
import { TestSlidesTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `TestSlides` services.
 */
interface TestSlidesAddedServices {
  parser: {
    TokenBuilder: TestSlidesTokenBuilder;
    ValueConverter: CommonValueConverter;
  };
}

/**
 * Union of Langium default services and `TestSlides` services.
 */
export type TestSlidesServices = LangiumCoreServices & TestSlidesAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `TestSlides` services.
 */
export const TestSlidesModule: Module<
  TestSlidesServices,
  PartialLangiumCoreServices & TestSlidesAddedServices
> = {
  parser: {
    TokenBuilder: () => new TestSlidesTokenBuilder(),
    ValueConverter: () => new CommonValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createTestSlidesServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  TestSlides: TestSlidesServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const TestSlides: TestSlidesServices = inject(
    createDefaultCoreModule({ shared }),
    TestSlidesDiagramGeneratedModule,
    TestSlidesModule
  );
  shared.ServiceRegistry.register(TestSlides);
  return { shared, TestSlides };
}
