import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { CommonValueConverter } from '../common/valueConverter.js';
import {
  MermaidGeneratedSharedModule,
  VisSlidesDiagramGeneratedModule,
} from '../generated/module.js';
import { VisSlidesTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `VisSlides` services.
 */
interface VisSlidesAddedServices {
  parser: {
    TokenBuilder: VisSlidesTokenBuilder;
    ValueConverter: CommonValueConverter;
  };
}

/**
 * Union of Langium default services and `VisSlides` services.
 */
export type VisSlidesServices = LangiumCoreServices & VisSlidesAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `VisSlides` services.
 */
export const VisSlidesModule: Module<
  VisSlidesServices,
  PartialLangiumCoreServices & VisSlidesAddedServices
> = {
  parser: {
    TokenBuilder: () => new VisSlidesTokenBuilder(),
    ValueConverter: () => new CommonValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createVisSlidesServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  VisSlides: VisSlidesServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const VisSlides: VisSlidesServices = inject(
    createDefaultCoreModule({ shared }),
    VisSlidesDiagramGeneratedModule,
    VisSlidesModule
  );
  shared.ServiceRegistry.register(VisSlides);
  return { shared, VisSlides };
}
