import type {
  DefaultSharedCoreModuleContext,
  LangiumCoreServices,
  LangiumSharedCoreServices,
  Module,
  PartialLangiumCoreServices,
} from 'langium';
import {
  EmptyFileSystem,
  createDefaultCoreModule,
  createDefaultSharedCoreModule,
  inject,
} from 'langium';

import { CommonValueConverter } from '../common/valueConverter.js';
import { MermaidGeneratedSharedModule, VisualDiagramGeneratedModule } from '../generated/module.js';
import { VisualDiagramTokenBuilder } from './tokenBuilder.js';

/**
 * Declaration of `VisualDiagram` services.
 */
interface VisualDiagramAddedServices {
  parser: {
    TokenBuilder: VisualDiagramTokenBuilder;
    ValueConverter: CommonValueConverter;
  };
}

/**
 * Union of Langium default services and `VisualDiagram` services.
 */
export type VisualDiagramServices = LangiumCoreServices & VisualDiagramAddedServices;

/**
 * Dependency injection module that overrides Langium default services and
 * contributes the declared `VisualDiagram` services.
 */
export const VisualDiagramModule: Module<
  VisualDiagramServices,
  PartialLangiumCoreServices & VisualDiagramAddedServices
> = {
  parser: {
    TokenBuilder: () => new VisualDiagramTokenBuilder(),
    ValueConverter: () => new CommonValueConverter(),
  },
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 * @param context - Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createVisualDiagramServices(
  context: DefaultSharedCoreModuleContext = EmptyFileSystem
): {
  shared: LangiumSharedCoreServices;
  VisualDiagram: VisualDiagramServices;
} {
  const shared: LangiumSharedCoreServices = inject(
    createDefaultSharedCoreModule(context),
    MermaidGeneratedSharedModule
  );
  const VisualDiagram: VisualDiagramServices = inject(
    createDefaultCoreModule({ shared }),
    VisualDiagramGeneratedModule,
    VisualDiagramModule
  );
  shared.ServiceRegistry.register(VisualDiagram);
  return { shared, VisualDiagram };
}
